mypyblog/korisnici/routes.py
from flask import Blueprint, redirect, url_for, flash, render_template, request
from flask_login import current_user, login_user, logout_user, login_required

from mypyblog import bcrypt, db
from mypyblog.korisnici.forms import RegistrationaForma, LoginForma, AzurirajProfilForma, ZahtevajResetFormu, \
    ResetPasswordForma
from mypyblog.korisnici.utils import sacuvaj_sliku, posalji_reset_email
from mypyblog.models import Korisnik, Post

korisnici = Blueprint('korisnici', __name__)

@korisnici.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationaForma()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        korisnik = Korisnik(korisnicko_ime=form.korisnicko_ime.data, email=form.email.data, password=hashed_password)
        db.session.add(korisnik)
        db.session.commit()
        flash(f'Nalog je uspesno napravljen za korisnico ime: {form.korisnicko_ime.data}! Mozete se ulogovati!', 'success')
        return redirect(url_for('korisnici.login'))
    return render_template('register.html', title='Registracija', form=form)

@korisnici.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForma()
    if form.validate_on_submit():
        korisnik = Korisnik.query.filter_by(email=form.email.data).first()
        if korisnik and bcrypt.check_password_hash(korisnik.password, form.password.data):
            login_user(korisnik, remember=form.zapamti_me.data)
            sledeca_strana = request.args.get('next')
            if sledeca_strana:
                return redirect(sledeca_strana)
            else:
                return redirect(url_for('main.home'))
        else:
            flash('Neuspesno logovanje. Molim vas da proverite unete podatke.', 'danger')
    return render_template('login.html', title='Login', form=form)

@korisnici.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@korisnici.route("/profil", methods=['GET', 'POST'])
@login_required
def profil():
    form = AzurirajProfilForma()
    if form.validate_on_submit():

        if form.slika.data:
            slika_fajl = sacuvaj_sliku(form.slika.data)
            current_user.slika_fajl = slika_fajl

        current_user.korisnicko_ime = form.korisnicko_ime.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Vas profil je uspesno azuriran', 'success')
        return redirect(url_for('korisnici.profil'))

    elif request.method == 'GET':
        form.korisnicko_ime.data = current_user.korisnicko_ime
        form.email.data = current_user.email
    slika_fajl = url_for('static', filename='profilne_slike/' + current_user.slika_fajl)
    return render_template("profil.html", title='Profil', slika_fajl=slika_fajl, form=form)


@korisnici.route("/korisnik/<string:korisnicko_ime>")
def postovi_korisnika(korisnicko_ime):
    page = request.args.get('page', 1, type=int)
    korisnik = Korisnik.query.filter_by(korisnicko_ime=korisnicko_ime).first_or_404()
    posts = Post.query.filter_by(author=korisnik).order_by(Post.datum_posta.desc()).paginate(page=page, per_page=5)
    return render_template('korisnicki_post.html', posts=posts, korisnik=korisnik)



@korisnici.route("/restart_passworda", methods=['GET', 'POST'])
def zahtev_za_restart():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ZahtevajResetFormu()
    if form.validate_on_submit():
        korisnik = Korisnik.query.filter_by(email=form.email.data).first()
        posalji_reset_email(korisnik)
        flash('E-mail sa instrukcijama za restartovanje passworda je poslat.', 'success')
        return redirect(url_for('korisnici.login'))

    return render_template('password_restart_zahtev.html', title='Restart Passworda', form=form)


@korisnici.route("/restart_passworda/<token>", methods=['GET', 'POST'])
def restart_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    korisnik = Korisnik.proveri_rest_token(token)
    if korisnik is None:
        flash('Token nije validan ili je istekao', 'warning')
        return redirect(url_for('korisnici.zahtev_za_restart'))
    form = ResetPasswordForma()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        korisnik.password = hashed_password
        db.session.commit()
        flash(f'Password je uspesno azuriran, mozete se ulogovati!', 'success')
        return redirect(url_for('korisnici.login'))
    return render_template('restart_token.html', title='Restart Passworda', form=form)

mypyblog/main/routes.py
from flask import Blueprint, request, render_template
from mypyblog.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.datum_posta.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

mypyblog/postovi/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, abort, request
from flask_login import login_required, current_user

from mypyblog import db
from mypyblog.models import Post
from mypyblog.postovi.forms import PostForma

postovi = Blueprint('postovi', __name__)

@postovi.route("/post/novi", methods=['GET', 'POST'])
@login_required
def novi_post():
    form = PostForma()
    if form.validate_on_submit():
        post = Post(naslov=form.naslov.data, sadrzaj=form.sadrzaj.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post je napravljen', 'success')
        return redirect(url_for('main.home'))
    return render_template("novi_post.html", title='Novi Post', legend='Azuriraj Post', form=form)


@postovi.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.naslov, post=post)

@postovi.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def azuriraj_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForma()
    if form.validate_on_submit():
        post.naslov = form.naslov.data
        post.sadrzaj = form.sadrzaj.data
        db.session.commit()
        flash('Vas post je uspesno azuriran!', 'success')
        return redirect(url_for('postovi.post', post_id=post.id))
    elif request.method == 'GET':
        form.naslov.data = post.naslov
        form.sadrzaj.data = post.sadrzaj
    return render_template('novi_post.html', title="Azuriraj Post", form=form, legend='Azuriraj Post')


@postovi.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def obrisi_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Uspesno obrisan post!', 'success')
    return redirect(url_for('main.home'))

mypyblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

mypyblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
         <div class="col-md-10 mb-5 border p-3">
             <h3 class="article-title border-bottom pb-2"><a href="{{ url_for('postovi.post', post_id=post.id) }}">{{ post.naslov }}</a></h3>
             <img src="{{ url_for('static', filename='profilne_slike/' + post.author.slika_fajl) }}" alt="post img" class="rounded-circle article-img m-3">

             <a class="mr-2 h4" href="{{ url_for('korisnici.postovi_korisnika', korisnicko_ime=post.author.korisnicko_ime) }}">{{ post.author.korisnicko_ime }}</a>
             <small class="text-muted">{{ post.datum_posta.strftime('%d/%m/%Y, %H:%M:%S') }}</small>
             <article class="border-top pt-3 lead"><p>{{ post.sadrzaj }}</p></article>
         </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-primary mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-primary mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {%endif%}
        {%else%}
            ...
        {%endif%}
    {% endfor %}
{% endblock content %}

mypyblog/templates/korisnicki_post.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3 border-bottom pb-3 col-md-10">Postovi od strane {{ korisnik.korisnicko_ime }} ({{posts.total}})</h1>
    {% for post in posts.items %}
         <div class="col-md-10 mb-5 border p-3">
             <h3 class="article-title border-bottom pb-2"><a href="{{ url_for('postovi.post', post_id=post.id) }}">{{ post.naslov }}</a></h3>
             <img src="{{ url_for('static', filename='profilne_slike/' + post.author.slika_fajl) }}" alt="post img" class="rounded-circle article-img m-3">

             <a class="mr-2 h4" href="{{ url_for('korisnici.postovi_korisnika', korisnicko_ime=post.author.korisnicko_ime) }}">{{ post.author.korisnicko_ime }}</a>
             <small class="text-muted">{{ post.datum_posta.strftime('%d/%m/%Y, %H:%M:%S') }}</small>
             <article class="border-top pt-3 lead"><p>{{ post.sadrzaj }}</p></article>
         </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-primary mb-4" href="{{ url_for('korisnici.postovi_korisnika', korisnicko_ime=korisnik.korisnicko_ime, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-primary mb-4" href="{{ url_for('korisnici.postovi_korisnika', korisnicko_ime=korisnik.korisnicko_ime, page=page_num) }}">{{ page_num }}</a>
            {%endif%}
        {%else%}
            ...
        {%endif%}
    {% endfor %}
{% endblock content %}

mypyblog/templates/layout.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  {% if title %}
      <title>The MyPy Blog - {{ title }}</title>
  {% else %}
      <title>The MyPy Blog</title>
  {% endif %}

  <meta name="description" content="The MyPy Blog About Us">
  <meta name="author" content="Sasa Tesic">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    <header class="mb-3">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                 <a class="navbar-brand" href="{{url_for('main.home')}}">MyPy Blog</a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>

                  <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                        <a class="nav-link h5" href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link h5" href="{{url_for('main.about')}}">About</a>
                      </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link h5" href="{{url_for('postovi.novi_post')}}">Novi Post </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link h5" href="{{url_for('korisnici.profil')}}">Profil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link h5" href="{{url_for('korisnici.logout')}}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link h5" href="{{url_for('korisnici.login')}}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link h5" href="{{url_for('korisnici.register')}}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                  </div>
            </div>
        </nav>
    </header>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-dismissible alert-{{ category }}">
                      <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {% if category == 'success' %}
                            <h4 class="alert-heading h1">Uspeh!</h4>
                        {% elif category == 'info'%}
                            <h4 class="alert-heading">Obavestenje!</h4>
                        {% else %}
                            <h4 class="alert-heading">Greska!</h4>
                        {% endif %}
                      <p class="mb-0 h5">{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

mypyblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="border p-5">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-4 border-bottom">Ulogujte Se!</legend>
                <br>
                <div class="form-group h5 {{ 'has-danger' if form.email.errors }}">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.email.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.password.errors }}">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.password.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{form.zapamti_me(class="form-check-input")}}
                    {{form.zapamti_me.label(class="form-check-label")}}
                </div>
                <div class="form-group border-bottom pb-3 mt-2">
                    {{ form.submit(class="btn btn-success") }}
                </div>
                <p class="text-muted ml-2">
                    <a href="{{ url_for('korisnici.zahtev_za_restart') }}">Zaboravili Ste Lozinku?</a>
                </p>
            </fieldset>
        </form>

        <div class="pt-3">
        <small class="text-muted h5">
            Nemate nalog? <a href="{{ url_for('korisnici.register') }}" class="ml-2">Registrujte se</a>
        </small>
    </div>
    </div>
{% endblock content %}

mypyblog/templates/novi_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="border p-5">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-4 border-bottom">{{ legend }}!</legend>
                <br>
                <div class="form-group h5 {{ 'has-danger' if form.naslov.errors }}">
                    {{ form.naslov.label(class="form-control-label") }}

                    {% if form.naslov.errors %}
                        {{ form.naslov(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.naslov.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.naslov(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.sadrzaj.errors }}">
                    {{ form.sadrzaj.label(class="form-control-label") }}

                    {% if form.sadrzaj.errors %}
                        {{ form.sadrzaj(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.sadrzaj.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.sadrzaj(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary form-control") }}
                </div>
            </fieldset>
        </form>
    </div>
    </div>
{% endblock content %}

mypyblog/templates/password_restart_zahtev.html
{% extends "layout.html" %}
{% block content %}
    <div class="border p-5">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-4 border-bottom">Restart Passworda!</legend>
                <br>
                <div class="form-group h5 {{ 'has-danger' if form.email.errors }}">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.email.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group border-bottom pb-3 mt-2">
                    {{ form.submit(class="btn btn-success") }}
                </div>
            </fieldset>
        </form>
    </div>
    </div>
{% endblock content %}

mypyblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <div class="col-md-10 mb-5 border-secondary p-3">
         <h1 class="article-title text-primary">{{ post.naslov }}</h1>
         <img src="{{ url_for('static', filename='profilne_slike/' + post.author.slika_fajl) }}" alt="post img" class="rounded-circle article-img m-3">
         <a class="mr-2 h4" href="{{ url_for('korisnici.postovi_korisnika', korisnicko_ime=post.author.korisnicko_ime) }}">{{ post.author.korisnicko_ime }}</a>
         <small class="text-muted">{{ post.datum_posta.strftime('%d/%m/%Y, %H:%M:%S') }}</small>
        {% if post.author == current_user %}
            <a class="btn btn-outline-primary btn-sm m-3" href="{{ url_for('postovi.azuriraj_post', post_id=post.id ) }}">Azuriraj Post</a>
        <button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#exampleModal">Obrisi Post</button>

        <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Brisanje Posta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Da li ste sigurni da zelite da obrisete ovaj post?</p>
              </div>
              <div class="modal-footer">
                  <form action="{{ url_for('postovi.obrisi_post', post_id=post.id) }}" method="POST">
                      <input type="submit" class="btn btn-danger" value="Obrisi">
                  </form>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Zatvori</button>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
         <article class="border-top pt-3 lead"><p>{{ post.sadrzaj }}</p></article>
     </div>
{% endblock content %}

mypyblog/templates/profil.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ slika_fajl }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.korisnicko_ime }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
      <div class="p-3">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-2 border-bottom">Azuriranje Profila</legend>
                <br>
                <div class="form-group h5 {{ 'has-danger' if form.korisnicko_ime.errors }}">
                    {{ form.korisnicko_ime.label(class="form-control-label") }}

                    {% if form.korisnicko_ime.errors %}
                        {{ form.korisnicko_ime(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.korisnicko_ime.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.korisnicko_ime(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.email.errors }}">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.email.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.email.errors }}">
                    {{ form.slika.label() }}
                    {{ form.slika(class="form-control-file mt-3 mb-3") }}
                    {% if form.slika.errors %}
                        {%for errors in form.slika.errors%}
                            <span class="text-danger">{{ errors }}</span><br>
                        {% endfor %}
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group border-bottom pb-3">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
    </div>
    </div>
{% endblock content %}

mypyblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="border p-5">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-4 border-bottom">Pridruzite Nam Se Danas!</legend>
                <br>
                <div class="form-group h5 {{ 'has-danger' if form.korisnicko_ime.errors }}">
                    {{ form.korisnicko_ime.label(class="form-control-label") }}

                    {% if form.korisnicko_ime.errors %}
                        {{ form.korisnicko_ime(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.korisnicko_ime.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.korisnicko_ime(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.email.errors }}">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.email.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.password.errors }}">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.password.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.confirm_password.errors }}">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for errors in form.confirm_password.errors %}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group border-bottom pb-3">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
        <div class="pt-3">
        <small class="text-muted h5">
            Imate nalog? <a href="{{ url_for('korisnici.login') }}" class="ml-2">Ulogujte se</a>
        </small>
        </div>
    </div>
{% endblock content %}

mypyblog/templates/restart_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="border p-5">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-4 border-bottom">Restart Passworda!</legend>
                <br>
                <div class="form-group h5 {{ 'has-danger' if form.password.errors }}">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%for errors in form.password.errors%}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group h5 {{ 'has-danger' if form.confirm_password.errors }}">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for errors in form.confirm_password.errors %}
                                <span>{{ errors }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group border-bottom pb-3 mt-2">
                    {{ form.submit(class="btn btn-success") }}
                </div>
            </fieldset>
        </form>
    </div>
    </div>
{% endblock content %}